# Generated by Django 2.2.16 on 2022-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20220308_2137'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genretitle',
            name='unique_name_owner',
        ),
        migrations.AddConstraint(
            model_name='genretitle',
            constraint=models.UniqueConstraint(fields=('title_id', 'genre_id'), name='unique_title_genre'),
        ),
    ]
