# Generated by Django 2.2.16 on 2022-03-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='qwe2313', unique=True),
            preserve_default=False,
        ),
    ]
